-- CreateTable
CREATE TABLE "OkrItem" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "code" TEXT,
    "title" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "project" TEXT,
    "status" TEXT NOT NULL DEFAULT 'Chưa bắt đầu',
    "startDate" DATETIME,
    "endDate" DATETIME,
    "owner" TEXT,
    "stakeholder" TEXT,
    "chotFlag" TEXT,
    "isOptional" BOOLEAN NOT NULL DEFAULT false,
    "strategicPillar" TEXT,
    "deadline" TEXT,
    "pic" TEXT,
    "scope" TEXT,
    "description" TEXT,
    "successMetric" TEXT,
    "targetValue" TEXT,
    "measureFormula" TEXT,
    "corporateKRLinkage" TEXT,
    "notes" TEXT,
    "progressPct" REAL NOT NULL DEFAULT 0,
    "parentId" TEXT,
    CONSTRAINT "OkrItem_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "OkrItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
